---
all:
  children:
    validator_health_remediation:
      vars:
        ansible_port: 2522
      hosts:
        host1:
          ansible_host: 192.0.2.10
        host2:
          ansible_host: 192.0.2.11
        host3:
          ansible_host: 192.0.2.12
        host4:
          ansible_host: 192.0.2.13
