{
 "title": "Hayek Validators Metrics",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "server",
    "label": "Server",
    "query": {
     "query": "SHOW TAG VALUES FROM nodemonitor WITH KEY=\"host\""
    }
   },
   { "name": "inter", "label": "Sampling", "query": "10s,30s,1m,2m,5m,10m,30m,1h" },
   {
    "name": "pubkey",
    "label": "pubkey",
    "query": "hayek-testnet (hyt8ZV...) : hyt8ZV8sweXyxva1S9tibC4iTaixfFfx8icpGXtNDUJ , hayek-mainnet (hykfH9...) : hykfH9jUQqe2yqv3VqVAK5AmMYqrmMWmdwDcbfsm6My,"
   },
   {
    "name": "netif",
    "label": "Network Interface",
    "query": {
     "query": "SHOW TAG VALUES FROM \"net\" WITH KEY = \"interface\" WHERE host =~ /$server/"
    }
   },
   {
    "name": "cpu",
    "label": "CPU",
    "query": {
     "query": "SHOW TAG VALUES FROM \"cpu\" WITH KEY = \"cpu\" WHERE host =~ /$server/"
    }
   }
  ]
 },
 "panels": [
  { "title": "Solana Network Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "SOL/USDT Price",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "nodemonitor",
     "select": [
      [
       { "params": [ "solanaPrice" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "pubkey::tag", "operator": "=~", "value": "/^$pubkey$/" }
     ]
    }
   ]
  },
  {
   "title": "Current Epoch",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "nodemonitor",
     "query": "SELECT \"epoch\" FROM \"nodemonitor\" WHERE (\"host\" = 'Hayek-03-dl-debug') AND $timeFilter",
     "select": [
      [
       { "params": [ "epoch" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "pubkey::tag", "operator": "=~", "value": "/^$pubkey$/" }
     ]
    }
   ]
  },
  {
   "title": "Epoch% Progress",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 7, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "nodemonitor",
     "query": "SELECT \"pctEpochElapsed\" FROM \"autogen\".\"nodemonitor\" WHERE (\"host\" = 'Hayek-03-dl-debug') AND $timeFilter",
     "select": [
      [
       { "params": [ "pctEpochElapsed" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "pubkey::tag", "operator": "=~", "value": "/^$pubkey$/" }
     ]
    }
   ]
  },
  {
   "title": " Epoch end in",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "nodemonitor",
     "select": [
      [
       { "params": [ "time_to_epoch_end_human" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "pubkey::tag", "operator": "=~", "value": "/^$pubkey$/" }
     ]
    }
   ]
  },
  { "title": "Stake & Scoring Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Active Stake",
   "type": "stat",
   "description": "Active stake on the validator.",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "SOL" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "nodemonitor",
     "select": [
      [
       { "params": [ "activatedStake" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "pubkey::tag", "operator": "=~", "value": "/^$pubkey$/" }
     ]
    }
   ]
  },
  {
   "title": "Activating stake",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 4, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "activating_stake", "language": "jsonata", "name": "Activating stake", "type": "number" }
     ],
     "method": "GET"
    }
   ]
  },
  {
   "title": "Deactivating stake",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 7, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "fields": [
      { "jsonPath": "deactivating_stake", "language": "jsonata", "name": "Deactivating stake", "type": "number" }
     ],
     "method": "GET"
    }
   ]
  },
  {
   "title": "Score",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 11, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "Stakewiz",
     "measurement": "nodemonitor",
     "select": [
      [
       { "params": [ "wiz_score" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "pubkey::tag", "operator": "=~", "value": "/^$pubkey$/" }
     ]
    }
   ]
  },
  {
   "title": "Ranking",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 8 },
   "targets": [
    {
     "alias": "Stakewiz Rank",
     "measurement": "nodemonitor",
     "select": [
      [
       { "params": [ "rank" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "pubkey::tag", "operator": "=~", "value": "/^$pubkey$/" }
     ]
    },
    {
     "alias": "Jpool TVC Rank",
     "measurement": "nodemonitor",
     "select": [
      [
       { "params": [ "tvc_rank" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "pubkey::tag", "operator": "=~", "value": "/^$pubkey$/" }
     ]
    }
   ]
  },
  {
   "title": "Balance on Vote Account",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "SOL" } },
   "targets": [
    {
     "alias": "Balance",
     "measurement": "nodemonitor",
     "select": [
      [
       { "params": [ "validatorVoteBalance" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "pubkey::tag", "operator": "=~", "value": "/^$pubkey$/" }
     ]
    }
   ]
  },
  {
   "title": "Active Stake",
   "type": "timeseries",
   "description": "Active stake on the validator.",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "SOL" } },
   "targets": [
    {
     "alias": "Stake",
     "measurement": "nodemonitor",
     "select": [
      [
       { "params": [ "activatedStake" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "pubkey::tag", "operator": "=~", "value": "/^$pubkey$/" }
     ]
    }
   ]
  },
  { "title": "Operational Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Vote Account Balance",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "SOL" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nodemonitor",
     "select": [
      [
       { "params": [ "validatorVoteBalance" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "pubkey::tag", "operator": "=~", "value": "/^$pubkey$/" }
     ]
    }
   ]
  },
  {
   "title": "Identity Account Balance",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 3, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "SOL" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "nodemonitor",
     "select": [
      [
       { "params": [ "validatorBalance" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "pubkey::tag", "operator": "=~", "value": "/^$pubkey$/" }
     ]
    }
   ]
  },
  {
   "title": "Commissions",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 7, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "nodemonitor",
     "select": [
      [
       { "params": [ "commission" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "pubkey::tag", "operator": "=~", "value": "/^$pubkey$/" }
     ]
    }
   ]
  },
  {
   "title": "Version ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "nodemonitor",
     "select": [
      [
       { "params": [ "gossip_version" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "pubkey::tag", "operator": "=~", "value": "/^$pubkey$/" }
     ]
    }
   ]
  },
  {
   "title": "Balance on Identity Acccount",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "SOL" } },
   "targets": [
    {
     "alias": "Balance",
     "measurement": "nodemonitor",
     "select": [
      [
       { "params": [ "validatorBalance" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "pubkey::tag", "operator": "=~", "value": "/^$pubkey$/" }
     ]
    }
   ]
  },
  { "title": "Revenue Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nodemonitor",
     "query": "SELECT last(\"status\") FROM \"autogen\".\"nodemonitor\" WHERE (\"pubkey\"::tag =~ /^$pubkey$/) AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "status" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "pubkey::tag", "operator": "=~", "value": "/^$pubkey$/" }
     ]
    }
   ]
  },
  {
   "title": "Using JITO",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "nodemonitor",
     "select": [
      [
       { "params": [ "is_jito" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "pubkey::tag", "operator": "=~", "value": "/^$pubkey$/" }
     ]
    }
   ]
  },
  {
   "title": "Leader Slots",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Total",
     "measurement": "nodemonitor",
     "query": "SELECT last(\"leader_slot_count\") \nFROM \"autogen\".\"nodemonitor\" \nWHERE (\"pubkey\"::tag =~ /^$pubkey$/) AND $timeFilter \nGROUP BY time($__interval) fill(previous)",
     "select": [
      [
       { "params": [ "leader_slot_count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "pubkey::tag", "operator": "=~", "value": "/^$pubkey$/" }
     ]
    },
    {
     "alias": "Produced ",
     "measurement": "nodemonitor",
     "select": [
      [
       { "params": [ "leaderSlots" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "pubkey::tag", "operator": "=~", "value": "/^$pubkey$/" }
     ]
    },
    {
     "alias": "Skipped",
     "measurement": "nodemonitor",
     "select": [
      [
       { "params": [ "skippedSlots" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "pubkey::tag", "operator": "=~", "value": "/^$pubkey$/" }
     ]
    }
   ]
  },
  {
   "title": "Skiprate",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "nodemonitor",
     "select": [
      [
       { "params": [ "pctSkipped" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "pubkey::tag", "operator": "=~", "value": "/^$pubkey$/" }
     ]
    }
   ]
  },
  {
   "title": "Next Leader Slot",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 15, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "nodemonitor",
     "select": [
      [
       { "params": [ "time_to_next_leader_slot_s" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "pubkey::tag", "operator": "=~", "value": "/^$pubkey$/" }
     ]
    }
   ]
  },
  {
   "title": "Leader Slots Next Epoch",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 19, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Total",
     "measurement": "nodemonitor",
     "select": [
      [
       { "params": [ "next_epoch_leader_slot_count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "pubkey::tag", "operator": "=~", "value": "/^$pubkey$/" }
     ]
    }
   ]
  },
  {
   "title": "Last 10 Leader Slots",
   "type": "table",
   "gridPos": { "h": 5, "w": 23, "x": 0, "y": 36 },
   "targets": [
    {
     "measurement": "blockmetrics",
     "query": "SELECT produced, reward, slot, epoch\nFROM blockmetrics\nWHERE (\"pubkey\"::tag =~ /^$pubkey$/)\nORDER BY time DESC\nLIMIT 80\n",
     "select": [
      [
       { "params": [ "reward" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "pubkey::tag", "operator": "=~", "value": "/^$pubkey$/" }
     ]
    }
   ]
  },
  {
   "title": "Jito MEV rewards per epoch ",
   "type": "table",
   "gridPos": { "h": 5, "w": 23, "x": 0, "y": 41 },
   "targets": [
    {
     "measurement": "blockmetrics",
     "query": "SELECT \n  LAST(jito_mev_rewards_sol) AS jito_mev_rewards_sol,\n  LAST(jito_mev_rewards_lamports) AS jito_mev_rewards_lamports,\n  LAST(jito_operator_rewards_sol) AS jito_operator_rewards_sol,\n  LAST(jito_mev_commission_bps) AS jito_mev_commission_bps\nFROM jito_mev_epochs\nWHERE (\"pubkey\"::tag =~ /^$pubkey$/)\nGROUP BY epoch\nORDER BY DESC\nLIMIT 20",
     "select": [
      [
       { "params": [ "reward" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "pubkey::tag", "operator": "=~", "value": "/^$pubkey$/" }
     ]
    }
   ]
  },
  {
   "title": "Blocks reward per epoch (Last 10 epoch)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "blockmetrics",
     "query": "SELECT SUM(\"reward\")\nFROM \"blockmetrics\"\nWHERE (\"pubkey\"::tag =~ /^$pubkey$/)\n  AND \"epoch\" != '823'\nGROUP BY \"epoch\"\n",
     "select": [
      [
       { "params": [ "reward" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "pubkey::tag", "operator": "=~", "value": "/^$pubkey$/" }
     ]
    }
   ]
  },
  {
   "title": "% Cluster Total Delinquent",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "% Total Delinquent",
     "measurement": "nodemonitor",
     "select": [
      [
       { "params": [ "pctTotDelinquent" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "pubkey::tag", "operator": "=~", "value": "/^$pubkey$/" }
     ]
    }
   ]
  },
  {
   "title": "My Credits",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "Credits",
     "groupBy": [
      { "params": [ "host::tag" ], "type": "tag" }
     ],
     "measurement": "nodemonitor",
     "query": "SELECT derivative(\"credits\", 1m) FROM \"autogen\".\"nodemonitor\" WHERE (\"pubkey\"::tag =~ /^$pubkey$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "credits" ], "type": "field" },
       { "params": [ "1m" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "pubkey::tag", "operator": "=~", "value": "/^$pubkey$/" }
     ]
    }
   ]
  },
  {
   "title": "Vote Performace",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "Hayek Vote Performance at $tag_host",
     "measurement": "nodemonitor",
     "query": "SELECT \"pctVote\" / 16 FROM \"autogen\".\"nodemonitor\" WHERE (\"pubkey\"::tag =~ /^$pubkey$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "pctVote" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=", "value": "Hayek-01-dl-debug" }
     ]
    },
    {
     "alias": "% Cluster Non-Delinquent Nodes",
     "query": "SELECT (100 - \"pctTotDelinquent\") FROM \"nodemonitor\" WHERE (\"pubkey\"::tag =~ /^$pubkey$/) AND $timeFilter "
    }
   ]
  },
  {
   "title": "My Leaderslots",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "Leaderslots",
     "measurement": "nodemonitor",
     "select": [
      [
       { "params": [ "leaderSlots" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "pubkey::tag", "operator": "=~", "value": "/^$pubkey$/" }
     ]
    },
    {
     "alias": "Skipped",
     "measurement": "nodemonitor",
     "select": [
      [
       { "params": [ "skippedSlots" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$server$/" }
     ]
    }
   ]
  },
  {
   "title": "My Skiprate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "My Skiprate",
     "measurement": "nodemonitor",
     "query": "SELECT \"pctSkipped\" FROM \"autogen\".\"nodemonitor\" WHERE (\"host\" = 'Hayek-02-dl') AND $timeFilter",
     "select": [
      [
       { "params": [ "pctSkipped" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "pubkey::tag", "operator": "=~", "value": "/^$pubkey$/" }
     ]
    },
    {
     "alias": "Cluster Skiprate",
     "measurement": "nodemonitor",
     "query": "SELECT \"pctTotSkipped\" FROM \"nodemonitor\" WHERE (\"host\" =~ /^$server$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "pctTotSkipped" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "pubkey::tag", "operator": "=~", "value": "/^$pubkey$/" }
     ]
    }
   ]
  },
  {
   "title": "Credits Current Epoch",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "Credits ",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "nodemonitor",
     "query": "SELECT \"validatorCreditsCurrent\" FROM \"autogen\".\"nodemonitor\" WHERE (\"pubkey\"::tag =~ /^$pubkey$/) AND $timeFilter ",
     "select": [
      [
       { "params": [ "validatorCreditsCurrent" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "pubkey::tag", "operator": "=~", "value": "/^$pubkey$/" }
     ]
    }
   ]
  },
  {
   "title": "Host presence – $pubkey",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 11, "x": 0, "y": 77 },
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "nodemonitor",
     "query": "SELECT MEAN(\"validatorCreditsCurrent\") / MEAN(\"validatorCreditsCurrent\") AS present\nFROM \"autogen\".\"nodemonitor\"\nWHERE \"pubkey\" =~ /^$pubkey$/ AND $timeFilter\nGROUP BY time($__interval), \"host\" fill(null)\n",
     "select": [
      [
       { "params": [ "validatorCreditsCurrent" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "pubkey::tag", "operator": "=~", "value": "/^$pubkey$/" }
     ]
    }
   ]
  }
 ]
}